favorite 로직 구현
f-lab-edu/last-order pull request #18
Opened 2022-12-23 11:25 UTC by JoYuKang

### 💡 개요
 - favorite 로직 구현
 
### 📑 작업 사항
 - favorite 로직 구현
 - 예외처리 추가
 - build 수정

2022-12-23 11:53 UTC, f-lab-lyan requested changes
간략하게 리뷰를 달아봤습니다. 전반적으로 PR 크기도 그렇고 로직단위로 잘 잘라서 PR을 만드신 것 같네요. 코멘트만 확인 부탁 드립니다.

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/controller/FavoriteController.java
> +    @PostMapping("/add/{storeId}")
이 부분은 POST 자체가 Add의 의미를 가지기 때문에 `{storeId}`만으로도 충분하지 않을까요?

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/controller/FavoriteController.java
> +    @DeleteMapping("/delete/{favoriteId}")
same as the above

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/controller/FavoriteController.java
> +    public void addFavorite(@PathVariable Long storeId){
어떤 리턴 밸류를 원할지 모르겠지만, 보통 POST로 추가를 하면, 같은 내용을 리턴하는 것이 API를 호출하는 입장에서 편리하게 이용할 수 있습니다.

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/controller/FavoriteController.java
> +    public void deleteFavorite(@PathVariable Long favoriteId){
same as the above

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/controller/advice/FavoriteControllerAdvice.java
> +@RestControllerAdvice(assignableTypes = {FavoriteController.class})
이렇게 하는 것도 나쁘지 않은데, 이렇게 되면, Controller가 하나씩 늘어날때마다 ControllerAdvice도 하나씩 늘어나게 되니까, 보통은 Controller안에 해당 ExceptionHandler를 추가하는 것이 코드 양의 측면에서 보면 더 좋을 것 같네요.

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/dto/SearchFavoriteResponse.java
> +    }
컨스트럭터와 `setFavoriteInfor`를 하나로 합치는 것이 의미를 전달하는 면에서 더 유리할 것 같습니다. 그렇게 되면, 각각의 변수들도 전부 final로 선언할 수 있게 되고, 그럼 자연스럽게 Response는 한번에 만들어서 리턴하기 위한 용도로만 쓰인다는 본래의 목적을 잘 전달할 수 있지 않을까요?

아래의 코드를 보면, 왜 이렇게 했을지 상상이 되긴 하는데, 아래 로직을 수정해서라도 response를 final로 만드는게 좋을 것 같습니다.

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/service/FavoriteService.java
> +    }
이 메소드는 크게 두 가지 역할을 하는데, 하나는 storeId가 제대로 되어 있는지 확인하는 것이고, 다른 하나는 Store entity를 리턴하는 것이예요. 그래서 이름은 checkStore인데, 실제로는 Store를 리턴하게 구현이 된 것이죠. 이럴 때는

```suggestion
    private Optional<Store> getStore(Long storeId) {
        return storeRepository.findById(storeId);
    }
```

이렇게 하고, 이 메소드를 부르는 쪽에서 저 메소드에 값이 정확히 들어있는지 스스로 확인하게 만드는게 더 명확한 코드 일 것 같습니다.

2022-12-23 11:53 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/service/FavoriteService.java
> +    public Long addFavorite(Long storeId) {
이 메소드를 특별히 아이디만 리턴하게 만든 이유가 있을까요?

2022-12-23 12:08 UTC, f-lab-lyan commented
슬랙 연동 테스트

2022-12-24 13:36 UTC, JoYuKang commented on last-order-api/src/main/java/com/flab/favorite/controller/FavoriteController.java
> +    @PostMapping("/add/{storeId}")
아하 add부분이 필요없는거 같네요! 
수정하겠습니다!

2022-12-24 13:40 UTC, JoYuKang commented on last-order-api/src/main/java/com/flab/favorite/dto/SearchFavoriteResponse.java
> +    }
아래 로직을 수정하는 방법으로 final을 넣을 수 있는 코드로 수정하겠습니다!

2022-12-24 13:47 UTC, JoYuKang commented on last-order-api/src/main/java/com/flab/favorite/service/FavoriteService.java
> +    public Long addFavorite(Long storeId) {
void와 Long을 고민해봤는데 테스트 중 return값을 받는 것이 더 인지하기 편해서 사용했습니다.

2022-12-24 16:30 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/service/FavoriteService.java
> +    public Long addFavorite(Long storeId) {
그렇군요. 그렇다면 아예 entity를 리턴하는 게 더 좋지 않을까요? 새로운 favorite을 추가한 이후에 그엔티티를 리턴하년 다시 아이디로 검색해서 찾을 필요는 없을 것 같네요.

2022-12-26 01:23 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/dto/SearchFavoriteResponse.java
> +    private String description;
```suggestion
    private final Long storeId;

    private final String storeName;

    private final double reviewScore;

    private final String description;
```

2022-12-26 01:25 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/dto/SearchFavoriteResponse.java
> +    public SearchFavoriteResponse(Favorite favorite) {
```suggestion
    public SearchFavoriteResponse(Long storeId, String storeName, double reviewScore, String description) {
```

2022-12-26 01:25 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/dto/SearchFavoriteResponse.java
> +    private String description;
DTO의 response니까 final로 하는 것이 좋아보여요.

2022-12-26 01:27 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/dto/SearchFavoriteResponse.java
> +    public void setFavoriteInfo(Store store) {
강제성을 주려면, 이 메소드 보다는 컨스트럭터에 추가하는게 더 좋아보입니다.

2022-12-26 01:31 UTC, f-lab-lyan commented on last-order-api/src/main/java/com/flab/favorite/service/FavoriteService.java
> +            searchFavoriteResponse.setFavoriteInfo(checkStore(searchFavoriteResponse.getStoreId()));
```suggestion
        favoriteRepository.findAllByUserId(1L).stream().map( favorite -> {
           Store store = checkStore(favorite.getStoreId());
           return new SearchFavoriteResponse(store.getId(), store...., store...., ...);
        });
```

2023-01-03 06:39 UTC, merged